(define (problem p1)
	(:domain world-of-blocks)
	(:objects a b c d e f g h)
	(:init
		(na-ziemi a)
		(na-ziemi b)
		(na-ziemi c)
		(na-ziemi d)
		(na-ziemi e)
		(na-ziemi f)
		(na-ziemi g)
		(na-ziemi h)
		(puste a)
		(puste b)
		(puste c)
		(puste d)
		(puste e)
		(puste f)
		(puste g)
		(puste h)
	)
	(:goal
		(and
			(na-ziemi a)
    		(not (na-ziemi b))
    		(not (na-ziemi c))
    		(not (na-ziemi d))
    		(not (na-ziemi e))
    		(not (na-ziemi f))
    		(not (na-ziemi g))
    		(not (na-ziemi h))
    		(puste f)
    		(not (puste a))
    		(not (puste b))
    		(not (puste c))
    		(not (puste d))
    		(not (puste e))
    		(not (puste g))
    		(not (puste h))
		)
	)
)


