(define
    (problem p1)
    (:domain merry)
    (:objects
        k1 k2 k3 k4 k5 k6 k7 k8 k9
        p1 p2 p3 p4 p5 p6 p7 p8 p9
        A B C D E F G H I
        o1 o2 o3 o4 o5 o6 o7 o8 o9 o10 o11 o12 o13 o14
        zielony czerwony pomaranczowy rozowy niebieski
    )
    (:init
        (poziomo p1 p2)
        (poziomo p2 p3)
        (poziomo p4 p5)
        (poziomo p5 p6)
        (poziomo p7 p8)
        (poziomo p8 p9)
        
        (pionowo p1 p4)
        (pionowo p4 p7)
        (pionowo p2 p5)
        (pionowo p5 p8)
        (pionowo p3 p6)
        (pionowo p6 p9)
        
        (na k5 p1)
        (na k4 p2)
        (na k1 p3)
        (na k8 p4)
        (na k9 p5)
        (na k3 p6)
        (na k7 p7)
        (na k2 p8)
        (na k6 p9)
        
        (falszywy k9)
        
        (mozna-przejsc A B pomaranczowy)
        (mozna-przejsc A C czerwony)
        (mozna-przejsc B D pomaranczowy)
        (mozna-przejsc C A czerwony)
        (mozna-przejsc C E zielony)
        (mozna-przejsc D F zielony)
        (mozna-przejsc E C zielony)
        (mozna-przejsc E F niebieski)
        (mozna-przejsc E H czerwony)
        (mozna-przejsc F D zielony)
        (mozna-przejsc F E niebieski)
        (mozna-przejsc F I niebieski)
        (mozna-przejsc F G rozowy)
        (mozna-przejsc H E czerwony)
        (mozna-przejsc H I niebieski)
        (mozna-przejsc I H niebieski)
        (mozna-przejsc I F niebieski)
        
        (kolor o1 zielony)
        (kolor o2 rozowy)
        (kolor o3 pomaranczowy)
        (kolor o4 niebieski)
        
        (kolor o5 zielony)
        (kolor o6 czerwony)
        (kolor o7 niebieski)
        (kolor o8 zielony)
        (kolor o9 niebieski)
        (kolor o10 niebieski)
        (kolor o11 zielony)
        (kolor o12 czerwony)
        (kolor o13 pomaranczowy)
        (kolor o14 niebieski)
        
        (w o1 A)
        (w o2 B)
        (w o3 C)
        (w o4 C)
        (w o5 D)
        (w o6 D)
        (w o7 E)
        (w o8 E)
        (w o9 F)
        (w o10 F)
        (w o11 H)
        (w o12 H)
        (w o13 I)
        (w o14 I)
        
        (aktualnie F)
    )
    (:goal (and
        (na k1 p1)
        (na k2 p2)
        (na k3 p3)
        (na k4 p4)
        (na k5 p5)
        (na k6 p6)
        (na k7 p7)
        (na k8 p8)
        (rozwiazana)
        (aktualnie G)
    ))
)

